// Login
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';

// Create Admin
export const CREATE_ADMIN_PENDING = 'CREATE_ADMIN_PENDING';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_FAIL = 'CREATE_ADMIN_FAIL';

// Logout
export const LOGOUT = 'LOGOUT';

// List Users
export const LIST_USERS = 'LIST_USERS';
export const UPDATE_USER_STATE_SUCCESS = 'UPDATE_USER_STATE_SUCCESS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

// List Skills
export const LIST_SKILLS_SUCCESS = 'LIST_SKILLS_SUCCESS';
export const LIST_SKILLS_PENDING = 'LIST_SKILLS_PENDING';
export const LIST_SKILLS_FAIL = 'LIST_SKILLS_FAIL';

// Add skills
export const ADD_NEW_SKILL = 'ADD_NEW_SKILL';

export const UPDATE_STATUS_SKILL = 'UPDATE_STATUS_SKILL';
export const UPDATE_SKILL_NAME = 'UPDATE_SKILL_NAME';

// Contract
export const LIST_CONTRACTS = 'LIST_CONTRACTS';
export const UPDATE_CONTRACTS_SUCCESS = 'UPDATE_CONTRACTS_SUCCESS';

// Admin
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';

// Messages
export const LIST_MESSAGES = 'LIST_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';