// Login
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';

// Create Admin
export const CREATE_ADMIN_PENDING = 'CREATE_ADMIN_PENDING';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_FAIL = 'CREATE_ADMIN_FAIL';

// Logout
export const LOGOUT = 'LOGOUT';

// List Users
export const LIST_USERS = 'LIST_USERS';
export const UPDATE_USER_STATE_SUCCESS = 'UPDATE_USER_STATE_SUCCESS';
export const CHANGE_PAGE_USERS = 'CHANGE_PAGE_USERS';

// List Skills
export const LIST_SKILLS_SUCCESS = 'LIST_SKILLS_SUCCESS';
export const LIST_SKILLS_PENDING = 'LIST_SKILLS_PENDING';
export const LIST_SKILLS_FAIL = 'LIST_SKILLS_FAIL';
export const CHANGE_PAGE_SKILLS = 'CHANGE_PAGE_SKILLS';

// Add skills
export const ADD_NEW_SKILL = 'ADD_NEW_SKILL';

export const UPDATE_STATUS_SKILL = 'UPDATE_STATUS_SKILL';
export const UPDATE_SKILL_NAME = 'UPDATE_SKILL_NAME';

// Contract
export const LIST_CONTRACTS = 'LIST_CONTRACTS';
export const UPDATE_CONTRACTS_SUCCESS = 'UPDATE_CONTRACTS_SUCCESS';
export const CHANGE_PAGE_CONTRACTS = 'CHANGE_PAGE_CONTRACTS';


// Admin
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export const UPDATE_PHOTO_SUCCESS = 'UPDATE_PHOTO_SUCCESS';

// Messages
export const LIST_MESSAGES = 'LIST_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';

// Chat
export const ADD_CHAT = 'ADD_CHAT';
export const ADD_BOX = 'ADD_BOX';
export const CLEAR_CHAT = 'CLEAR_CHAT';
export const CLEAR_BOX = 'CLEAR_BOX';
export const CONTRACT_DETAIL = 'CONTRACT_DETAIL';

// Dashboard
export const GET_CHART_DATA = 'GET_CHART_DATA';
export const GET_TOP_SALES_BY_TEACHER = 'GET_TOP_SALES_BY_TEACHER';
export const GET_TOP_SALES_BY_SKILL = 'GET_TOP_SALES_BY_SKILL';
export const GET_SUMMARY_REPORT = 'GET_SUMMARY_REPORT';